[workspace]
members = ["librex", "rex"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/b0b-io/rex"

[workspace.dependencies]
# Dependencies will be added incrementally as needed during implementation
