[package]
name = "librex"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
chrono-humanize = "0.2.3"
humansize = "2.1.3"
oci-spec = "0.8.3"
thiserror = "1.0"


[dev-dependencies]
serde_json = "1.0"

