name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Check documentation
        run: just docs

      - name: Check formatting
        run: just fmt check

      - name: Run clippy
        run: just lint
